# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyscanex.ui'
#
# Created: Sun Jun 08 16:31:17 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(862, 566)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/question.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 206, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 206, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 206, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(201, 206, 193))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFiles = QtGui.QWidget()
        self.tabFiles.setObjectName(_fromUtf8("tabFiles"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabFiles)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableFiles = QtGui.QTableWidget(self.tabFiles)
        self.tableFiles.setAlternatingRowColors(True)
        self.tableFiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableFiles.setColumnCount(4)
        self.tableFiles.setObjectName(_fromUtf8("tableFiles"))
        self.tableFiles.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableFiles.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(3, item)
        self.horizontalLayout.addWidget(self.tableFiles)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/file_manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabFiles, icon1, _fromUtf8(""))
        self.tabConsultation = QtGui.QWidget()
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 212, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 212, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 212, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 212, 195))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.tabConsultation.setPalette(palette)
        self.tabConsultation.setObjectName(_fromUtf8("tabConsultation"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tabConsultation)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonReset = QtGui.QPushButton(self.tabConsultation)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow_refresh_small.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonReset.setIcon(icon2)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout.addWidget(self.pushButtonReset, 0, 1, 1, 1)
        self.pushButtonStop = QtGui.QPushButton(self.tabConsultation)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonStop.setIcon(icon3)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.gridLayout.addWidget(self.pushButtonStop, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tabConsultation)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setMinimumSize(QtCore.QSize(400, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.comboBoxquestion = QtGui.QComboBox(self.groupBox_2)
        self.comboBoxquestion.setGeometry(QtCore.QRect(10, 20, 381, 22))
        self.comboBoxquestion.setObjectName(_fromUtf8("comboBoxquestion"))
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(400, 83))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBoxAnswers = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxAnswers.setGeometry(QtCore.QRect(10, 20, 381, 22))
        self.comboBoxAnswers.setObjectName(_fromUtf8("comboBoxAnswers"))
        self.pushButtonNext = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonNext.setGeometry(QtCore.QRect(260, 50, 131, 23))
        self.pushButtonNext.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/arrow_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButtonNext.setIcon(icon4)
        self.pushButtonNext.setAutoRepeat(False)
        self.pushButtonNext.setObjectName(_fromUtf8("pushButtonNext"))
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.listDecisions = QtGui.QListWidget(self.groupBox_5)
        self.listDecisions.setObjectName(_fromUtf8("listDecisions"))
        self.verticalLayout_7.addWidget(self.listDecisions)
        self.gridLayout_3.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listFacts = QtGui.QListWidget(self.groupBox_6)
        self.listFacts.setObjectName(_fromUtf8("listFacts"))
        self.horizontalLayout_3.addWidget(self.listFacts)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 4, 1)
        self.groupBoxDecision = QtGui.QGroupBox(self.groupBox)
        self.groupBoxDecision.setMinimumSize(QtCore.QSize(350, 50))
        self.groupBoxDecision.setObjectName(_fromUtf8("groupBoxDecision"))
        self.plainDecisions = QtGui.QPlainTextEdit(self.groupBoxDecision)
        self.plainDecisions.setGeometry(QtCore.QRect(10, 20, 381, 192))
        self.plainDecisions.setObjectName(_fromUtf8("plainDecisions"))
        self.gridLayout_2.addWidget(self.groupBoxDecision, 2, 0, 2, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 4)
        self.verticalLayout_4.addLayout(self.gridLayout)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ask_and_answer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabConsultation, icon5, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toolBar.setFont(font)
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setEnabled(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon6)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/door_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon7)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCompile = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_lightning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompile.setIcon(icon8)
        self.actionCompile.setObjectName(_fromUtf8("actionCompile"))
        self.actionRun = QtGui.QAction(MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon9)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionDelete = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon10)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCompile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PyScanex", None))
        self.tableFiles.setSortingEnabled(True)
        item = self.tableFiles.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Plik", None))
        item = self.tableFiles.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Skompilowano?", None))
        item = self.tableFiles.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Rozmiar, bajt", None))
        item = self.tableFiles.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Dodano", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFiles), _translate("MainWindow", "Bazy wiedzy", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Odświeżenie", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Ukończ konsultację", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Pytanie:", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Odpowiedź:", None))
        self.pushButtonNext.setText(_translate("MainWindow", "Dalej", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Informacja:", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Możliwe decyzje:", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Fakty:", None))
        self.groupBoxDecision.setTitle(_translate("MainWindow", "Decyzja:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabConsultation), _translate("MainWindow", "Konsultacja", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAdd.setText(_translate("MainWindow", "Dodaj plik", None))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add new knowledge base to the system", None))
        self.actionExit.setText(_translate("MainWindow", "Powrót", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit from application", None))
        self.actionCompile.setText(_translate("MainWindow", "Skompiluj bazę", None))
        self.actionCompile.setToolTip(_translate("MainWindow", "Compile selected knowledge base", None))
        self.actionRun.setText(_translate("MainWindow", "Zacznij konsultacę", None))
        self.actionRun.setToolTip(_translate("MainWindow", "Run selected knowledge base", None))
        self.actionDelete.setText(_translate("MainWindow", "Usuń plik", None))
        self.actionDelete.setToolTip(_translate("MainWindow", "Delete knowledge base", None))

import resources_rc
