# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyscanex.ui'
#
# Created: Mon May 12 18:30:49 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(763, 545)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/question.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockNestingEnabled(False)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabFiles = QtGui.QWidget()
        self.tabFiles.setObjectName(_fromUtf8("tabFiles"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabFiles)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tableFiles = QtGui.QTableWidget(self.tabFiles)
        self.tableFiles.setAlternatingRowColors(True)
        self.tableFiles.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tableFiles.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableFiles.setColumnCount(3)
        self.tableFiles.setObjectName(_fromUtf8("tableFiles"))
        self.tableFiles.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableFiles.setHorizontalHeaderItem(2, item)
        self.horizontalLayout.addWidget(self.tableFiles)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/file_manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabFiles, icon1, _fromUtf8(""))
        self.tabCompiled = QtGui.QWidget()
        self.tabCompiled.setObjectName(_fromUtf8("tabCompiled"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabCompiled)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.tableCompiled = QtGui.QTableWidget(self.tabCompiled)
        self.tableCompiled.setObjectName(_fromUtf8("tableCompiled"))
        self.tableCompiled.setColumnCount(3)
        self.tableCompiled.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableCompiled.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableCompiled.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.tableCompiled.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.tableCompiled)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_green.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tabCompiled, icon2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButtonReset = QtGui.QPushButton(self.tab)
        self.pushButtonReset.setObjectName(_fromUtf8("pushButtonReset"))
        self.gridLayout.addWidget(self.pushButtonReset, 0, 1, 1, 1)
        self.pushButtonDisplay = QtGui.QPushButton(self.tab)
        self.pushButtonDisplay.setObjectName(_fromUtf8("pushButtonDisplay"))
        self.gridLayout.addWidget(self.pushButtonDisplay, 0, 0, 1, 1)
        self.pushButtonStop = QtGui.QPushButton(self.tab)
        self.pushButtonStop.setObjectName(_fromUtf8("pushButtonStop"))
        self.gridLayout.addWidget(self.pushButtonStop, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setMinimumSize(QtCore.QSize(350, 50))
        self.groupBox_2.setMaximumSize(QtCore.QSize(350, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.lineEditQuestion = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditQuestion.setGeometry(QtCore.QRect(10, 20, 331, 20))
        self.lineEditQuestion.setMinimumSize(QtCore.QSize(331, 20))
        self.lineEditQuestion.setReadOnly(True)
        self.lineEditQuestion.setObjectName(_fromUtf8("lineEditQuestion"))
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_3.setMinimumSize(QtCore.QSize(350, 83))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.comboBoxAnswers = QtGui.QComboBox(self.groupBox_3)
        self.comboBoxAnswers.setGeometry(QtCore.QRect(10, 20, 331, 22))
        self.comboBoxAnswers.setObjectName(_fromUtf8("comboBoxAnswers"))
        self.pushButtonNext = QtGui.QPushButton(self.groupBox_3)
        self.pushButtonNext.setGeometry(QtCore.QRect(180, 50, 161, 23))
        self.pushButtonNext.setObjectName(_fromUtf8("pushButtonNext"))
        self.gridLayout_2.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBoxDecision = QtGui.QGroupBox(self.groupBox)
        self.groupBoxDecision.setMinimumSize(QtCore.QSize(350, 50))
        self.groupBoxDecision.setObjectName(_fromUtf8("groupBoxDecision"))
        self.lineEditDecision = QtGui.QLineEdit(self.groupBoxDecision)
        self.lineEditDecision.setGeometry(QtCore.QRect(10, 20, 331, 20))
        self.lineEditDecision.setReadOnly(True)
        self.lineEditDecision.setObjectName(_fromUtf8("lineEditDecision"))
        self.gridLayout_2.addWidget(self.groupBoxDecision, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.listDecisions = QtGui.QListWidget(self.groupBox_5)
        self.listDecisions.setObjectName(_fromUtf8("listDecisions"))
        self.verticalLayout_7.addWidget(self.listDecisions)
        self.gridLayout_3.addWidget(self.groupBox_5, 2, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.listFacts = QtGui.QListWidget(self.groupBox_6)
        self.listFacts.setObjectName(_fromUtf8("listFacts"))
        self.horizontalLayout_3.addWidget(self.listFacts)
        self.gridLayout_3.addWidget(self.groupBox_6, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_3)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 4, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.textEditRule = QtGui.QTextEdit(self.groupBox_7)
        self.textEditRule.setReadOnly(True)
        self.textEditRule.setObjectName(_fromUtf8("textEditRule"))
        self.verticalLayout_8.addWidget(self.textEditRule)
        self.gridLayout_2.addWidget(self.groupBox_7, 3, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_2)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 4)
        self.verticalLayout_4.addLayout(self.gridLayout)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/ask_and_answer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setSizeIncrement(QtCore.QSize(0, 0))
        self.toolBar.setMovable(False)
        self.toolBar.setIconSize(QtCore.QSize(32, 32))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtGui.QAction(MainWindow)
        self.actionAdd.setEnabled(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon4)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/door_in.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon5)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionCompile = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_lightning.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCompile.setIcon(icon6)
        self.actionCompile.setObjectName(_fromUtf8("actionCompile"))
        self.actionRun = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_go.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon7)
        self.actionRun.setObjectName(_fromUtf8("actionRun"))
        self.actionDelete = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/database_delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDelete.setIcon(icon8)
        self.actionDelete.setObjectName(_fromUtf8("actionDelete"))
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionDelete)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionCompile)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionExit)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Scannex", None))
        self.tableFiles.setSortingEnabled(True)
        item = self.tableFiles.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Path", None))
        item = self.tableFiles.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableFiles.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Added", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFiles), _translate("MainWindow", "Knowledge Base Files", None))
        item = self.tableCompiled.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Path", None))
        item = self.tableCompiled.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Size", None))
        item = self.tableCompiled.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Compiled", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCompiled), _translate("MainWindow", "Compiled Knowledge Base Files", None))
        self.pushButtonReset.setText(_translate("MainWindow", "Reset", None))
        self.pushButtonDisplay.setText(_translate("MainWindow", "Display", None))
        self.pushButtonStop.setText(_translate("MainWindow", "Stop", None))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Quesiton:", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Answer:", None))
        self.pushButtonNext.setText(_translate("MainWindow", "Next", None))
        self.groupBoxDecision.setTitle(_translate("MainWindow", "Decision", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Progress Information:", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Possible decisions:", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Facts:", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Rule:", None))
        self.textEditRule.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Consultation", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))
        self.actionAdd.setToolTip(_translate("MainWindow", "Add new knowledge base to the system", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionExit.setToolTip(_translate("MainWindow", "Exit from application", None))
        self.actionCompile.setText(_translate("MainWindow", "Compile", None))
        self.actionCompile.setToolTip(_translate("MainWindow", "Compile selected knowledge base", None))
        self.actionRun.setText(_translate("MainWindow", "Run", None))
        self.actionRun.setToolTip(_translate("MainWindow", "Run selected knowledge base", None))
        self.actionDelete.setText(_translate("MainWindow", "Delete", None))
        self.actionDelete.setToolTip(_translate("MainWindow", "Delete knowledge base", None))

import resources_rc
